server:
  port: 8080

api:
  cookie: "https://fc.yahoo.com"

database:
  postgres: "db_finalproject"

spring.datasource:
  # driverClassName: "org.hibernate.dialect.PostgreSQLDialect"
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/${database.postgres}"
  username: "postgres"
  password: "admin1234"
  
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update

spring.data.redis:
  host: localhost
  port: 6379
  database: 0
  timeout: 60000
  password: